import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

import React from 'react';
import DashboardLayout from './components/layout/DashboardLayout';
import { ThemeProvider } from './components/ui/ThemeProvider';
import { SolanaWalletProvider } from './components/SolanaWalletProvider';

function DashboardLayoutWrapper({ children }: { children: React.ReactNode }) {
	return <DashboardLayout>{children}</DashboardLayout>;
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				suppressHydrationWarning={true}
			>
				<ThemeProvider>
					<SolanaWalletProvider>
						<DashboardLayoutWrapper>{children}</DashboardLayoutWrapper>
					</SolanaWalletProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
